label: Cifar10 Partial
image: tensorflow/tensorflow:latest-gpu
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -c 'from keras.datasets import cifar10; cifar10.load_data()'


docker:
    binds:
        - "/Users/marc/bude/deepkit-python-sdk/:/deepkit-sdk"
    env:
        - PYTHONPATH=/deepkit-sdk

install_files:
    - requirements.txt
      
#resources:
#    cpu: 2
#    memory: 2

parameters:
    lr: 0.8
    batch_size: 128
    epochs: 8
    train_samples: 15000
    test_samples: 15000

command: ls -al && python model.py
