image: python:3.6
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -c 'from keras.datasets import cifar10; cifar10.load_data()'

docker:
    binds:
        - "../../:/deepkit-sdk"
    env:
        - PYTHONPATH=/deepkit-sdk

install_files:
    - requirements.txt

parameters:
    lr: 0.1
    batch_size: 100
    epochs: 100
    train_samples: 5000
    test_samples: 5000

command: ls -al && python model.py
