label: Cifar10 Partial
image: tensorflow/tensorflow:latest-gpu
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -c 'from keras.datasets import cifar10; cifar10.load_data()'


docker:
    binds:
        - "/Users/marc/bude/deepkit-python-sdk/:/deepkit-sdk"
    env:
        - PYTHONPATH=/deepkit-sdk

install_files:
    - requirements.txt


output: saved_models

resources:
    cpu: 4
    memory: 4

parameters:
    lr: 0.8
    batch_size: 128
    epochs: 5
    train_samples: 10000
    test_samples: 10000

command: ls -al && python model.py
